apiVersion: v1
kind: Service
metadata:
  name: healthcare-backend-service
  namespace: healthcare-app
spec:
  type: LoadBalancer
  selector:
    app: healthcare-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
