name: CI/CD Pipeline - Healthcare Frontend (Azure)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Log in to Azure Container Registry (ACR)
      - name: Azure Container Registry Login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Step 5: Build and push Docker image to ACR
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/healthcare-frontend:latest ./frontend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/healthcare-frontend:latest

      # Step 6: Deploy image to Azure Web App for Containers
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_NAME }}.azurecr.io/healthcare-frontend:latest
